#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 3 ]]; then
    echo "usage: $0 <tag> <checksums.txt> <output-formula>" >&2
    exit 1
fi

TAG=$1
CHECKSUMS_FILE=$2
OUTPUT_FILE=$3

PROJECT_NAME="gumroad-cli"
REPOSITORY="antiwork/gumroad-cli"
VERSION="${TAG#v}"

checksum_for() {
    local archive=$1
    local checksum

    checksum=$(awk -v file="$archive" '$2 == file || $2 == ("*" file) { print $1; exit }' "$CHECKSUMS_FILE")
    if [[ -z "$checksum" ]]; then
        echo "missing checksum for ${archive} in ${CHECKSUMS_FILE}" >&2
        exit 1
    fi

    printf '%s\n' "$checksum"
}

archive_url() {
    local os=$1
    local arch=$2

    printf 'https://github.com/%s/releases/download/%s/%s_%s_%s.tar.gz' \
        "$REPOSITORY" "$TAG" "$PROJECT_NAME" "$os" "$arch"
}

darwin_arm64_sha=$(checksum_for "${PROJECT_NAME}_darwin_arm64.tar.gz")
darwin_amd64_sha=$(checksum_for "${PROJECT_NAME}_darwin_amd64.tar.gz")
linux_arm64_sha=$(checksum_for "${PROJECT_NAME}_linux_arm64.tar.gz")
linux_amd64_sha=$(checksum_for "${PROJECT_NAME}_linux_amd64.tar.gz")

mkdir -p "$(dirname "$OUTPUT_FILE")"

cat >"$OUTPUT_FILE" <<EOF
# This file is generated by script/render-homebrew-formula.sh. DO NOT EDIT.
class Gumroad < Formula
  desc "CLI for the Gumroad API"
  homepage "https://github.com/${REPOSITORY}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "$(archive_url darwin arm64)"
      sha256 "${darwin_arm64_sha}"
    end
    on_intel do
      url "$(archive_url darwin amd64)"
      sha256 "${darwin_amd64_sha}"
    end
  end

  on_linux do
    on_arm do
      url "$(archive_url linux arm64)"
      sha256 "${linux_arm64_sha}"
    end
    on_intel do
      url "$(archive_url linux amd64)"
      sha256 "${linux_amd64_sha}"
    end
  end

  def install
    bin.install "gumroad"
    man1.install Dir["man/*.1"]
    generate_completions_from_executable(bin/"gumroad", "completion")
    (pwsh_completion/"gumroad.ps1").write Utils.safe_popen_read(bin/"gumroad", "completion", "powershell")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gumroad --version")
  end
end
EOF
